services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "4787:5432"

  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - POSTGRES_URL=db
    depends_on:
      - db

volumes:
  pgdata:
